/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dummy;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void resourceContents() throws Exception {
        final var fooResource = getClass().getClassLoader().getResourceAsStream("conf/foo.conf");
        final var fooContents = new String(fooResource.readAllBytes());
        assertTrue(fooContents.indexOf("hello") > 0, "%s does not contain \"hello\"".formatted(fooContents.trim()));
    }
}
